### ISSUE TITLE
Planes not counting for Bring It Down

### ISSUE THREAD

**Issue by KCManning** [maybe-hello-world/40k-roster-formatter#69]
When submitting a list with 2 Archeopter Fusilave for the Adeptus Mechanicus, the "Bring It Down" scoring section at the top of the sheet shows 4 fewer points than it should. (In my case, 5x Kastelan Robots, 5x Ironstrider Ballistarii, and 2x Archaeopter Fusilaves)
When the planes are not included, the other vehicles all show correctly.

**Comment by maybe-hello-world** [comment]
@KCManning may I ask you to provide the battlescribe list file as well?

**Comment by KCManning** [comment]
Happy to provide that!

**Comment by maybe-hello-world** [comment]
Well, I already found the problem :D
BSData developers forgot to add the keyword "Vehicle" to all admech flyers.
I submitted the bug in their repository, you can track the progress here: https://github.com/BSData/wh40k/issues/12038.

I think fixing the data itself is the best way to fix this problem instead of introducing workarounds or anything in my code, so I'll close this issue, but feel free to reopen it after some time if BSData developers wouldn't fix it.
